/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-07-14 08:45:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FreeBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Moble.*;
import Moble.DAOImpl;
import Moble.WishBoardVO;
import java.util.List;

public final class FreeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Moble");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Moble.DAOImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Moble.WishBoardVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");

	DAO dao = new DAOImpl();
	List<WishBoardVO> list = dao.getList();
	System.out.println(list.toString());

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>모블 게시판</title>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <title> 모블 자유 게시판(강 사)  </title>\r\n");
      out.write("        <link href=\"../CSS/FreeBoard.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- ****** 네비게이션 바 메뉴 ****** -->\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <header class=\"app-header\"> <!-- div태그를 써서 작성하여도 되지만 헤더를 이용하여 좀더 세세히 나눔 -->\r\n");
      out.write("                <h1 class=\"brand\">\r\n");
      out.write("                <a href=\"http://www.saramin.co.kr/zf_user/company-info/view/csn/1198632756/company_nm/(%EC%A3%BC)%EB%AA%A8%EB%B8%94/\" target=\"_blank\"> \r\n");
      out.write("                    <span class=\"logo-name\">Moble</span>\r\n");
      out.write("                        <!-- <SPAN>태그 인태그를 사용해서 위드나 헤이드 태그를 사용 DIV와의 차이 /\r\n");
      out.write("                        CSS로 모블 글씨의 변화를 주고자 함-->\r\n");
      out.write("                </a>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <ul class=\"nav\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#schedule\" target=\"_self\"> 학습자료 게시판</a></li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#gradeInfo\"> 출결 게시판</a> </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#goodStudenSt\"> 자유 게시판</a> </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link nav-right\" href=\"#stuInfo\"> 소원수리 게시판</a> </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button type=\"button\" class=\"button is-open\">\r\n");
      out.write("                    <img src=\"images/navigation-button.gif\" alt=\"메뉴 열기\">\r\n");
      out.write("                </button>\r\n");
      out.write("            </header>\r\n");
      out.write("            \r\n");
      out.write("\t\t<!-- ************ 표 내용 만들기  ************ -->\r\n");
      out.write("\t\t<main class=\"board-main\">\r\n");
      out.write("\t        <div class=\"boardtitle\">\r\n");
      out.write("\t        \t<p class=\"boardfont\">모블 자유 게시판</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- ****** 게시판 검색 ****** -->\r\n");
      out.write("\t\t\t<div class=\"container_search\" >\r\n");
      out.write("\t\t\t\t<!-- 글찾기  -->\r\n");
      out.write("\t\t\t\t<div class=\"inp_text\">\r\n");
      out.write("\t\t\t\t\t<select class = \"select_search\" name=\"choice\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"title\">제목</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"writer\">작성자</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"date\">날짜</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t       \t<label for=\"loginId\" class=\"screen_out\"></label>\r\n");
      out.write("\t\t\t       \t<input type=\"text\" id=\"loginId\" name=\"loginId\" placeholder=\"Search\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"location.href='viewAuthorTable.jsp'\">검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- ****** 게시판 내용 ****** -->\t\r\n");
      out.write("\t\t\t<div class=\"container_board\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"WriteFreeBoard.jsp\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table_board\" style=\"border:1px solid #dddddd\"> \r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"checks\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"keepLogin\" class=\"tableCulrom\"  name=\"keepLogin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"tableCulrom1\" style=\"border:1px solid #dddddd\">No</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"tableCulrom2\" style=\"border:1px solid #dddddd\">제 목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"tableCulrom3\" style=\"border:1px solid #dddddd\">내 용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"tableCulrom4\" style=\"border:1px solid #dddddd\">작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"tableCulrom5\" style=\"border:1px solid #dddddd\">날 짜</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");
 
								for(WishBoardVO vo : list) {
							
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th class=\"checks\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"keepLogin\" class=\"tableCulrom\"  name=\"keepLogin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(vo.get_Student_number() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(vo.get_Wish_Title() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(vo.get_Wish_Text() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(vo.get_Wish_id() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(vo.get_Wish_Date() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<!-- 글 작성 버튼   -->\r\n");
      out.write("\t\t\t\t\t<div class=\"post_button\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn-write\" value=\"글  삭제\" />\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- ****** 글 작성 버튼 ****** -->\r\n");
      out.write("\t\t\t\t<div class=\"Num_board\">\r\n");
      out.write("\t\t\t\t   \t<ul class=\"ul_board\"> \r\n");
      out.write("\t\t\t    \t\t<li class=\"li_board\"><a href=\"#\">[ 1 ]</a></li>\r\n");
      out.write("\t\t\t   \t\t\t<li class=\"li_board\"><a href=\"#\">[ 2 ]</a></li>\r\n");
      out.write("\t\t\t   \t\t\t<li class=\"li_board\"><a href=\"#\">[ 3 ]</a></li>\r\n");
      out.write("\t\t   \t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</main>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- ****** 하단 부 디자인 ****** -->\r\n");
      out.write("\t\t<div class=\"boxColor\">\r\n");
      out.write("\t\t\t<p>\"\"</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
