/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-07-15 06:45:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FreeBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class WriteFreeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");

      String Student_name = null;
      if(session.getAttribute("Student_name") != null ){
    	  Student_name = (String) session.getAttribute("Student_name");
      }
      out.print("Student_name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title> 모블 자유 게시판(학 생) </title>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<link href=\"../CSS/WriteFreeBoard.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\t\t<div class=\"boardtitle\">\r\n");
      out.write("\t\t\t<p class=\"boardfont\">모블 자유 게시판 글 작성</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <!-- ****** 네비게이션 바 메뉴 ****** -->\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <header class=\"app-header\"> <!-- div태그를 써서 작성하여도 되지만 헤더를 이용하여 좀더 세세히 나눔 -->\r\n");
      out.write("                <h1 class=\"brand\">\r\n");
      out.write("                <a href=\"http://www.saramin.co.kr/zf_user/company-info/view/csn/1198632756/company_nm/(%EC%A3%BC)%EB%AA%A8%EB%B8%94/\" target=\"_blank\"> \r\n");
      out.write("                    <span class=\"logo-name\">Moble</span>\r\n");
      out.write("                        <!-- <SPAN>태그 인태그를 사용해서 위드나 헤이드 태그를 사용 DIV와의 차이 /\r\n");
      out.write("                        CSS로 모블 글씨의 변화를 주고자 함-->\r\n");
      out.write("                </a>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <ul class=\"nav\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#schedule!name =\" target=\"_self\"> 학습자료 게시판</a></li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#gradeInfo\"> 출결 게시판</a> </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#goodStudenSt\"> 자유 게시판</a> </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link nav-right\" href=\"#stuInfo\"> 소원수리 게시판</a> </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button type=\"button\" class=\"button is-open\">\r\n");
      out.write("                    <img src=\"../images/navigation-button.gif\" alt=\"메뉴 열기\">\r\n");
      out.write("                </button>\r\n");
      out.write("            </header>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("           \t<!-- ****** 글 작성 ****** -->\r\n");
      out.write("           \t<div class=\"writeFreeBoard-main\">\r\n");
      out.write("           \t\t<div class=\"writeBoard\">\r\n");
      out.write("           \t\t\t<form method=\"post\" id=\"authForm\" action=\"insertWishBoard.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("           \t\t\t\t<!-- ****** 제목, 이름  입력 ****** -->\r\n");
      out.write("           \t\t\t\t<div class=\"fieldset_one\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_FreeWrite\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"inp_Title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class = \"boderTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"writeTitle\" >제 목 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"writeTitle\" name=\"writeTitle\" placeholder=\"Title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"inp_Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class = \"boderName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"writeName\">이 름 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"writeName\" name=\"writeName\" placeholder=\"Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- ****** 내용 입력  ****** -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"fieldset_two\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box_FreeWrite\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label >내 용 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"inp_Content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"writeContent\" name=\"writeContent\" cols=\"10\" rows=\"8\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- ****** 이름과 비밀번호 데리고 다니기 ****** -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"Student_number\" value= \"");
      out.print(request.getParameter("Student_number"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"Student_name\" value= \"");
      out.print( request.getParameter("Student_name"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- ****** 글 작성 버튼  ****** -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"fieldset_three\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn_Write\">글 작성</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn_Back\" onClick=\"location.href='FreeBoard.jsp'\" >돌아 가기</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("           \t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("           \t\t</div>\t\r\n");
      out.write("           \t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- ****** 하단부 디자인  ****** -->\r\n");
      out.write("\t\t<div class=\"boxColor\">\r\n");
      out.write("\t\t\t<p>\"\"</p>\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
